### ISSUE TITLE
ADAP3 Peak Detection doesnt work.

### ISSUE THREAD

**Issue by mlovas** [du-lab/ADAP-in-MZmine2#1]
"Error of task Peak recognition on _filename_: 'R computing error' during peak detection.
The _filename_ requires the "adap.peak.detection" R package, which couldn't be loaded - is it installed in R?"

Where can i find this package? Is it available?

**Comment by du-lab** [comment]
First, thank you for using and testing ADAP3 Peak Detection. 

Indeed, ADAP3 Peak Detection requires the adap.peak.detection R package. Recently, we have replaced "Peak list methods --> ADAP3 Peak Detection" with "Peak list methods --> Chromatogram deconvolution --> Algorithm --> Wavelet (ADAP-GC)". The latter is written in Java and C++ and will be faster than the R version. So I suggest that you use the latter.

**Comment by mlovas** [comment]
Thank you for your response! However, it doesnt work either.
"Peak deconvolution error(java.lang.NoClassDefFoundError: Could not initialize class dulab.adap.workflow.deconvolutioncpptools.UseMsconvertCWT@dulab.adap.workflow.Deconvolution.DeconvoluteSignal(Deconvolution.java:48))"
Do I need to install anything else besides ADAP-in-MzMine2? I have R-3.2.4 (with all metabolomics related packages) and Java JRE 8.

**Comment by du-lab** [comment]
What operating system are you using? ADAP-in-MZmine currently only runs on Mac due to the C++ code for peak picking. We are going to re-write in Java soon to make the program cross-platform.

**Comment by mortonjt** [comment]
Could you provide the link to the peak picking code?  It may be possible to make it conda installable, hence cross-platform
